server.name: "kibana"
server.port: 5601
server.host: "0.0.0.0"

#elasticsearch.hosts: ["http://node1:9200", "http://node2:9200", "http://node3:9200"] #release
elasticsearch.hosts: ["http://elasticsearch-es-node-1:9200"] #local
elasticsearch.username: "elastic/kibana"
elasticsearch.password: "password"
