server:
  port: ${local.server.port}

spring:
  config:
    activate:
      on-profile: local
  datasource:
      url: ${local.db.url}
      username: ${local.db.username}
      password: ${local.db.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        create_empty_composites:
            enabled: true
oauth:
  instagram:
    client_id: ${secret.instagram.client_id}
    client_secret: ${secret.instagram.client_secret}
    redirect_uri: ${secret.instagram.redirect_uri}

app-config:
  jwt :
    jwt-key: ${local.jwt.jwt_key}
    valid-time : ${local.jwt.valid_time}
  elastic:
    server-url: ${local.elastic.server_url}
    api-key : ${local.elastic.api_key}
    finger-print : ${local.elastic.finger_print}
    user-name: ${local.elastic.user_name}
    password: ${local.elastic.password}

aws-config:
  rds:
    secret-name : ${release.aws.rds.secret_name}
    region : ${release.aws.rds.region}
    db-url: ${release.db.url}
  credentials:
    access_key: ${secret.aws.access_key}
    secret_key: ${secret.aws.secret_key}
  s3:
    bucket: coclimb-media-bucket
    media:
      write_role_arn: "arn:aws:iam::085796513949:role/CoclimbS3Access"
      write_valid_time: 900 # sec
      read_role_arn: "arn:aws:iam::085796513949:role/CoclimbS3ReadOnly"
      read_valid_time: 3600 # sec
  cloudfront:
    host: ${local.aws.cloudfront.distribution_domain_name}
    secret-name: ${local.aws.cloudfront.secret_name}
    public_key_id: ${local.aws.cloudfront.public_key_id}
    region: ${local.aws.cloudfront.region}

logging:
  level:
    swm.s3.coclimb: debug
    sql: debug
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: ./logs/coclimb.log
  logback:
    rollingpolicy:
      max-file-size: 500KB # 로그 파일의 최대 크기이며, 크기가 넘어가면 새로운 로그파일 작성
      max-history: 30 #로그 파일 최대 보관 일자
      file-name-pattern: ./logs/coclimb.%d{yyyy-MM-dd}.%i.log
      total-size-cap: 1000MB

front_end:
  host: ${local.front_end.host}