spring:
  profiles:
    active: local
    include: secret

aws-config:
  rds:
    secret-name : ${release.aws.secret_name}
    region : ${release.aws.region}
    db-url: ${release.db.url}
  credentials:
    access_key: ${secret.aws.access_key}
    secret_key: ${secret.aws.secret_key}
  s3:
    media:
      write_role_arn: "arn:aws:iam::085796513949:role/CoclimbS3Access"
      write_valid_time: 900 # sec
      read_role_arn: "arn:aws:iam::085796513949:role/CoclimbS3ReadOnly"
      read_valid_time: 3600 # sec

cloud:
  aws:
    s3:
      bucket: ${secret.aws.bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloud_front:
      host: ${secret.aws.cloud_front_host}

file:
  download:
    path: /tmp/