spring:
  config:
    activate:
      on-profile: dev

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql-db:3306/coclimb_dev_db?useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
#    username: user
#    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug