spring:
  config:
    activate:
      on-profile: local
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
      url: ${local.db.url}
      username: ${local.db.username}
      password: ${local.db.password}
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

front_end:
  site_url: https://localhost:3000
