spring:
  profiles:
    active: local
    include: secret

aws-config:
  rds:
    secret-name : ${release.aws.secret_name}
    region : ${release.aws.region}
    db-url: ${release.db.url}
  credentials:
    access_key: ${secret.aws.access_key}
    secret_key: ${secret.aws.secret_key}


cloud:
  aws:
    s3:
      bucket: ${secret.aws.bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloud_front:
      host: ${secret.aws.cloud_front_host}

file:
  download:
    path: /tmp/