spring:
  profiles:
    active: local
    include: secret

aws-config:
  secret-name : ${release.aws.secret_name}
  region : ${release.aws.region}
  db-url: ${release.db.url}

cloud:
  aws:
    s3:
      bucket: ${secret.aws.bucket}
    credentials:
      access_key: ${secret.aws.access_key}
      secret_key: ${secret.aws.secret_key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloud_front:
      host: ${secret.aws.cloud_front_host}

file:
  download:
    path: /tmp/