spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#logging.level:
#  org.hibernate.SQL: debug