spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        create_empty_composites:
            enabled: true
#logging.level:
#  org.hibernate.SQL: debug