version: "3.7"

services:
  kibana:
    build: .
    restart: on-failure
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
#    network_mode: host #host모드는 리눅스환경에서만 사용 가능
    networks: #local
      - elasticsearch_default
networks:
  elasticsearch_default:
    external: true